@KakeiBro_API_HostAddress = http://localhost:5214
@KakeiBro_API_DEMO_HostAddress = https://kakeibro-api.dsbalderrama.top

GET {{KakeiBro_API_HostAddress}}/api/v1/weatherforecast/
Accept: application/json

###

GET {{KakeiBro_API_HostAddress}}/api/v1/auth/
Accept: application/json

###

GET {{KakeiBro_API_DEMO_HostAddress}}/api/v1/weatherforecast/
Accept: application/json

###
